name: local

networks:
  webnet:
    driver: bridge

volumes:
  mysql: # /var/lib/mysql
    driver: local
  phpmyadmin: # /etc/phpmyadmin
    driver: local

services:
  web:  # Web Service - https://hub.docker.com/r/xthukuh/local-web/tags
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # image: xthukun/local-web:latest
    image: xthukuh/local-web:v1.0.0
    container_name: web
    hostname: testing
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    volumes:
      # (required) dev home
      - ./www/:/etc/www/
      # (optional) expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
    working_dir: /etc/www/html/
    depends_on:
      - mysql
  mysql:  # MySQL Service - https://hub.docker.com/_/mariadb
    image: mariadb:11.7.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      TZ: Africa/Nairobi
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - webnet
  phpmyadmin:  # PHPMyAdmin (http://localhost:8080) - https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: local
    volumes:
      - phpmyadmin:/etc/phpmyadmin
    ports:
      - 8080:80
    networks:
      - webnet