name: local-web
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-web:latest
    container_name: web
    hostname: testing
    ports:
      - 80:80
      - 443:443
    volumes:
      # (required) dev home
      - ./www/:/etc/www/
      # (optional) expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
      # (optional) expose logs to host
      - ./docker/log/:/var/log/
